#!/usr/bin/env python3
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2012 Yannick Brosseau <yannick.brosseau@gmail.com>
# Bundled from lttng-ust v2.13.8 for use in Yocto recipes that lack
# lttng-ust-native. Run with: python3 lttng-gen-tp ...

from __future__ import print_function
import sys
import getopt
import re
import os
import subprocess


class Usage(Exception):
    def __init__(self, msg):
        self.msg = msg


class HeaderFile:
    HEADER_TPL = """
#undef LTTNG_UST_TRACEPOINT_PROVIDER
#define LTTNG_UST_TRACEPOINT_PROVIDER {providerName}

#undef LTTNG_UST_TRACEPOINT_INCLUDE
#define LTTNG_UST_TRACEPOINT_INCLUDE "./{headerFilename}"

#if !defined({includeGuard}) || defined(LTTNG_UST_TRACEPOINT_HEADER_MULTI_READ)
#define {includeGuard}

#include <lttng/tracepoint.h>

"""
    FOOTER_TPL = """
#endif /* {includeGuard} */

#include <lttng/tracepoint-event.h>
"""

    def __init__(self, filename, template):
        self.outputFilename = filename
        self.template = template

    def write(self):
        outputFile = open(self.outputFilename, "w")
        includeGuard = re.sub('[^0-9a-zA-Z]', '_', self.outputFilename.upper())
        outputFile.write(HeaderFile.HEADER_TPL.format(providerName=self.template.domain,
                                           includeGuard=includeGuard,
                                           headerFilename=self.outputFilename))
        outputFile.write(self.template.text)
        outputFile.write(HeaderFile.FOOTER_TPL.format(includeGuard=includeGuard))
        outputFile.close()


class CFile:
    FILE_TPL = """
#define LTTNG_UST_TRACEPOINT_CREATE_PROBES
/*
 * The header containing our LTTNG_UST_TRACEPOINT_EVENTs.
 */
#define LTTNG_UST_TRACEPOINT_DEFINE
#include "{headerFilename}"
"""

    def __init__(self, filename, template):
        self.outputFilename = filename
        self.template = template

    def write(self):
        outputFile = open(self.outputFilename, "w")
        headerFilename = self.outputFilename
        if headerFilename.endswith(".c"):
            headerFilename = headerFilename[:-2] + ".h"
        outputFile.write(CFile.FILE_TPL.format(headerFilename=headerFilename))
        outputFile.close()


class ObjFile:
    def __init__(self, filename, template):
        self.outputFilename = filename
        self.template = template

    def _detectCC(self):
        cc = ""
        if 'CC' in os.environ:
            cc = os.environ['CC']
            try:
                subprocess.call(cc.split(),
                                stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE)
            except OSError:
                print("Invalid CC environment variable")
                cc = ""
        else:
            for candidate in ("cc", "gcc"):
                try:
                    subprocess.call(candidate,
                                    stdout=subprocess.PIPE,
                                    stderr=subprocess.PIPE)
                    cc = candidate
                    break
                except OSError:
                    pass
        return cc

    def write(self):
        cFilename = self.outputFilename
        if cFilename.endswith(".o"):
            cFilename = cFilename[:-2] + ".c"
        cc = self._detectCC()
        if cc == "":
            raise RuntimeError("No C Compiler detected")
        cppflags = " " + os.environ.get('CPPFLAGS', "")
        cflags   = " " + os.environ.get('CFLAGS', "")
        command = cc + " -c" + cppflags + cflags + " -I. -o " + self.outputFilename + " " + cFilename
        if verbose:
            print("Compile command: " + command)
        subprocess.call(command.split())


class TemplateFile:
    def __init__(self, filename):
        self.domain = ""
        self.inputFilename = filename
        self.parseTemplate()

    def parseTemplate(self):
        with open(self.inputFilename, "r") as f:
            self.text = f.read()

        removeComments   = re.compile("#[^include].*$", flags=re.MULTILINE)
        self.text        = removeComments.sub("", self.text)
        removePreprocess = re.compile("#.*$", flags=re.MULTILINE)
        noPreprocess     = removePreprocess.sub("", self.text)
        removeLineComment = re.compile("\/\/.*$", flags=re.MULTILINE)
        nolinecomment    = removeLineComment.sub("", noPreprocess)
        cleantext        = re.sub(r"\s*", "", nolinecomment)
        nocomment        = re.sub(r"/\*.*?\*/", "", cleantext)
        entries          = re.split(r"^LTTNG_UST_TRACEPOINT_.*?", nocomment)

        for entry in entries:
            if entry != '':
                decomp = re.findall(r"(\w*?)\((\w*?),(\w*?),", entry)
                domain = decomp[0][1]
                if self.domain == "":
                    self.domain = domain
                elif self.domain != domain:
                    print("Warning: different domain provided (%s,%s)" % (self.domain, domain))


verbose = False

usage = """
 lttng-gen-tp - Generate the LTTng-UST header and source based on a simple template

 usage: lttng-gen-tp TEMPLATE_FILE [-o OUTPUT_FILE][-o OUTPUT_FILE]
"""


def main(argv=None):
    if argv is None:
        argv = sys.argv

    try:
        opts, args = getopt.gnu_getopt(argv[1:], "ho:av", ["help", "verbose"])
    except getopt.error as msg:
        print(str(msg), file=sys.stderr)
        return 2

    outputNames = []
    for o, a in opts:
        if o in ("-h", "--help"):
            print(usage)
            return 0
        if o == "-o":
            outputNames.append(a)
        if o in ("-v", "--verbose"):
            global verbose
            verbose = True

    if len(args) == 0:
        print("No template file given", file=sys.stderr)
        return 2

    doCFile = doHeader = doObj = False
    headerFilename = cFilename = objFilename = None

    if outputNames:
        if len(args) > 1:
            print("Cannot process more than one input if you specify an output")
            return 3
        for outputName in outputNames:
            if outputName.endswith(".h"):
                doHeader = True; headerFilename = outputName
            elif outputName.endswith(".c"):
                doCFile  = True; cFilename      = outputName
            elif outputName.endswith(".o"):
                doObj    = True; objFilename    = outputName
            else:
                print("output file type unsupported"); return 4
    else:
        doHeader = doCFile = doObj = True

    for arg in args:
        if not arg.endswith(".tp"):
            print(arg + " does not end in .tp. Skipping.")
            continue
        try:
            tpl = TemplateFile(arg)
        except IOError as e:
            print("Cannot read input file " + e.filename + " " + e.strerror)
            return -1
        try:
            if doHeader:
                name = headerFilename or re.sub(r"\.tp$", ".h", arg)
                HeaderFile(name, tpl).write()
            if doCFile:
                name = cFilename or re.sub(r"\.tp$", ".c", arg)
                CFile(name, tpl).write()
            if doObj:
                name = objFilename or re.sub(r"\.tp$", ".o", arg)
                ObjFile(name, tpl).write()
        except IOError as e:
            print("Cannot write output file " + e.filename + " " + e.strerror)
            return -1


if __name__ == "__main__":
    sys.exit(main())
